export const actionTypes = {
	ADD_ITEM: "ADD_ITEM",
	GET_ALL: "GET_ALL",
	DELETE_ITEM: "DELETE_ITEM",
	EDIT_ITEM:"EDIT_ITEM",
	CHECK_ITEM:"CHECK_ITEM",
	CHECK_ALL:"CHECK_ALL",
	DELETE_CHECKED:"DELETE_CHECKED",
	RENDER_PAGE:'RENDER_PAGE'
}