export const actionTypes = {
	ADD_ITEM: "ADD_ITEM",
	GET_ALL: "GET_ALL",
	DELETE_ITEM: "DELETE_ITEM",
	EDIT_ITEM:"EDIT_ITEM",
	CHECK_ITEM:"CHECK_ITEM",
	CHECK_ALL:"CHECK_ALL",
	DELETE_CHECKED:"DELETE_CHECKED",
	PAGE_COUNT : "PAGE_COUNT",
	CHANGE_PAGE:"PAGE_CHANGE",
	PREVIOUS_PAGE:"PREVIOUS_PAGE",
	NEXT_PAGE:"NEXT_PAGE"
}